name: build
on:
  push:
    branches:
      - v1.13.11-pr-76849
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    # build-tools is built from ../../tools/build-tools.Dockerfile
    container: kedacore/build-tools:v2
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: make release-images
